Application\MainBundle\Entity\Article:
    type: entity
    table: article
    repositoryClass: Application\MainBundle\Entity\ArticleRepository

    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            length: 255
        content:
            type: text
            nullable: true

    manyToMany:
        authors:
            targetEntity: Author
            mappedBy: articles
            cascade:
                - persist
