doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataClassificationBundle: ~
                    SonataMediaBundle: ~
                    FOSUserBundle: ~
                    SonataUserBundle: ~
                    ApplicationMainBundle: ~
                    ApplicationSonataClassificationBundle: ~
                    ApplicationSonataMediaBundle: ~
                    ApplicationSonataUserBundle: ~
                    
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
