parameters:
    twig.form.resources: []
    kernel.default_locale: %locale%
    
sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    impersonating:
        route:                default.home
        parameters:           { }