# https://github.com/egeloen/IvoryCKEditorBundle
# php ./app/console config:dump-reference IvoryCKEditorBundle

ivory_ck_editor:
    default_config: standard
    configs:
        standard:
            toolbar: standard
