services:
    form.type.translatable:
      class: Application\MainBundle\Form\TranslatedFieldType
      arguments: [ @service_container ]
      tags:
       - { name: form.type, alias: translatable_field }

    locale.listener:
        class: Application\MainBundle\EventListener\LocaleListener
        arguments:
            - @kernel
        tags:
            -
                name:   kernel.event_listener
                event:  kernel.controller
                method: handleCoreController