services:
    app.service.display.graph:
        class: Application\MainBundle\Service\DisplayGraph
        arguments: [ @service_container ]
    
    form.type.author:
      class: Application\MainBundle\Form\AuthorForm
      arguments: [ @service_container ]
      tags:
       - { name: form.type, alias: applicationmain_author_form }

    locale.listener:
        class: Application\MainBundle\EventListener\LocaleListener
        arguments:
            - @kernel
        tags:
            -
                name:   kernel.event_listener
                event:  kernel.controller
                method: handleCoreController