a2lix_translation_form:
    locale_provider: default                                    # [1]
    locales: [pl, en, fr, de]                                   # [1-a]
    default_locale: pl                                          # [1-b]
    required_locales: [pl]                                      # [1-c]
    manager_registry: doctrine                                  # [2]
    templating: "A2lixTranslationFormBundle::default.html.twig" # [3]